import yagmail

sender = "vv3151773@gmail.com"
app_password = "ermi zvzu vimv dwrs"

receiver = "akshatkumar67353@gmail.com"

yag = yagmail.SMTP(sender, app_password)

yag.send(
    to=receiver,
    subject="JKLC Human Detection Test",
    contents="""
Dear Concerned Team,

This is an automated alert generated by the JK Lakshmi Cement Human Detection Monitoring System.

A human presence has been detected by the surveillance camera.

====================================

DETECTION DETAILS

Event Type      : Human Detection
Detection Time  : {time.strftime('%d-%m-%Y %H:%M:%S')}
Camera Source   : Monitoring Camera
Alert Level     : High
Status          : Detection Confirmed

====================================

A screenshot captured during the detection event has been attached for review.

Recommended Actions:

1. Verify the detected individual.
2. Review camera footage if required.
3. Take necessary action as per company security policy.

This is an automatically generated alert.

Please do not reply to this email.

Regards,

Human Detection Monitoring System
JK Lakshmi Cement Ltd.
"""
)

print("Mail Sent Successfully!")